name: Story
on:
  workflow_call:
    inputs:
      skip_dist:
        description: 'True to skip the import fixing'
        type: boolean
jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Fix imports
        if: ${{ !inputs.skip_dist }}
        run: |
          [ -d "stories" ] && sed -i 's/..\/src/..\/dist/g' stories/*.stories.js || true
          [ -d "demo" ] && sed -i 's/..\/src/..\/dist/g' demo/*.js || true

      - name: Build storybook
        run: npm run storybook:build

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./storybook-static
          branch: gh-pages
          clean-exclude: pr
          force: false
